# Generated by Django 5.0 on 2023-12-28 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_eventregistration_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
    ]
