# Generated by Django 5.0 on 2023-12-29 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_eventregistration_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
