# Generated by Django 5.0 on 2023-12-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_registration_date_created_registration_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='attend_event_count',
            field=models.IntegerField(default=0),
        ),
    ]
