FROM nginx:latest

# COPY ./default.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /home/app/staticfiles
RUN mkdir -p /home/app/media


RUN mkdir -p /home/studystreak

# COPY ./../front/ /home/studystreak